// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInVsCode
{
    static class Vsix
    {
        public const string Id = "e99dde0e-e023-410d-bc5d-3f76db71e3f0";
        public const string Name = "Open in Visual Studio Code";
        public const string Description = "Adds a menu command that lets you open any solution, project, folder and file in Visual Studio Code.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vscode, code";
    }
}
